Calls to chdir(2) should be error checked
* Bad things can happen if you don't sanity check cd

diff --git a/bin/mad b/bin/mad
--- a/bin/mad
+++ b/bin/mad
@@ -118,14 +118,16 @@ install_all_remote() {
   local path=${0%/*}/../share/mad
   echo
   echo "  ... cloning repo"
-  cd /tmp && rm -fr mad-pages
-  git clone --depth 1 $REMOTE mad-pages
-  cd mad-pages
-  for page in *.md; do
-    echo "  ... installing $page"
-    cp -f $page $path/$page
-  done
-  echo "  ... complete"
+  cd /tmp && rm -fr mad-pages || exit 2
+  if git clone --depth 1 $REMOTE mad-pages && cd mad-pages; then
+    for page in *.md; do
+      echo "  ... installing $page"
+      cp -f $page $path/$page
+    done
+    echo "  ... complete"
+  else
+    echo "  ... failed!" >&2
+  fi
   echo
 }
 
@@ -136,10 +138,13 @@ install_all_remote() {
 install_mad() {
   echo
   echo "  ... cloning repo"
-  cd /tmp && rm -fr mad
+  cd /tmp && rm -fr mad || exit 3
   git clone --depth 1 $REMOTE_MAD mad
-  cd mad && make install
-  echo "  ... updated to $(mad --version)"
+  if cd mad && make install; then
+    echo "  ... updated to $(mad --version)"
+  else
+    echo "  ... failed to update!" >&2
+  fi
   echo
 }
 
